# Generated by Django 3.2.7 on 2021-10-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='like_user',
            new_name='like_users',
        ),
    ]
